{
 "title": "NodeTemplate-Api",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Requests",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "api_all_request_total" }
   ]
  },
  {
   "title": "Apdex Score",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "(\n  sum(rate(api_request_duration_milliseconds_bucket{le=\"25\",code=~\"^2..$\"}[1m]))\n+\n  sum(rate(api_request_duration_milliseconds_bucket{le=\"100\",code=~\"^2..$\"}[1m]))\n) / 2 / sum(rate(api_request_duration_milliseconds_count[1m]))"
    }
   ]
  },
  {
   "title": "Errors %",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "( api_all_errors_total / api_all_request_total ) * 100"
    }
   ]
  },
  {
   "title": "Requests in Processing",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "api_all_request_in_processing_total"
    }
   ]
  },
  {
   "title": "CPU %",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "nodejs_process_cpu_usage_percentage"
    }
   ]
  },
  {
   "title": "Heap Used, Mb",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(nodejs_process_memory_heap_used_bytes)/1048576"
    }
   ]
  },
  {
   "title": "Request and Error Rates (per sec)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum (api_request_total)", "legendFormat": "Request Rate" },
    {
     "expr": "sum (rate(api_request_total{code=~\"^5..$\"}[1m]))",
     "legendFormat": "5XX Errors Rate"
    },
    {
     "expr": "sum (rate(api_request_total{code=~\"^4..$\"}[1m]))",
     "legendFormat": "4XX Errors Rate"
    },
    {
     "expr": "sum (rate(api_request_total{code=~\"^2..$\"}[1m]))",
     "legendFormat": "2XX Success Rate"
    }
   ]
  },
  {
   "title": "Request rate by Method (per sec)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "sum by (method) (api_request_total)"
    }
   ]
  },
  {
   "title": "Top 3 API calls (by path)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(3, sum(irate(api_request_total[1m])) by (path))"
    }
   ]
  },
  {
   "title": "Request Duration (%)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "( sum(irate(api_request_duration_milliseconds_bucket{le=\"5\"}[1m])) /  sum(irate(api_request_duration_milliseconds_count[1m])) ) * 100",
     "legendFormat": "Duration < 5ms (%)"
    },
    {
     "expr": "( sum(irate(api_request_duration_milliseconds_bucket{le=\"10\"}[1m])) /  sum(irate(api_request_duration_milliseconds_count[1m])) ) * 100",
     "legendFormat": "Duration < 10ms (%)"
    },
    {
     "expr": "( sum(irate(api_request_duration_milliseconds_bucket{le=\"50\"}[1m])) /  sum(irate(api_request_duration_milliseconds_count[1m])) ) * 100",
     "legendFormat": "Duration < 50ms (%)"
    },
    {
     "expr": "( sum(irate(api_request_duration_milliseconds_bucket{le=\"100\"}[1m])) /  sum(irate(api_request_duration_milliseconds_count[1m])) ) * 100",
     "legendFormat": "Duration < 100ms (%)"
    }
   ]
  },
  {
   "title": "Apdex Score: target 25ms, tolerated: 100ms",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(\n  sum(irate(api_request_duration_milliseconds_bucket{le=\"25\",code=~\"^2..$\"}[1m]))\n+\n  (sum(irate(api_request_duration_milliseconds_bucket{le=\"100\",code=~\"^2..$\"}[1m]))/2)\n) / sum(irate(api_request_duration_milliseconds_count[1m]))"
    }
   ]
  },
  {
   "title": "Top 3 API Error Calls ( 4XX, by path)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(3, sum(rate(api_request_total{code=~\"^4..$\"}[1m])) by (path))"
    }
   ]
  }
 ]
}