name: Release Workflow
env:
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  DATABASE_USERNAME: root
  DATABASE_PASSWORD: my_password

on: ['pull_request']

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    services:
      mongodb:
        image: mongo:4.4.5
        env:
          MONGO_INITDB_ROOT_USERNAME: ${{ env.DATABASE_USERNAME }}
          MONGO_INITDB_ROOT_PASSWORD: ${{ env.DATABASE_PASSWORD }}
        ports:
          - 27017
        options: >-
          --health-cmd mongo
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - name: Use nodeJS ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Static Analysis
        run: yarn lint && yarn style:check

      - name: Run all tests
        env:
          DATABASE_ADDRESS: localhost
          DATABASE_USERNAME: ${{ env.DATABASE_USERNAME }}
          DATABASE_PASSWORD: ${{ env.DATABASE_PASSWORD }}
          DATABASE_PORT: ${{ job.services.mongodb.ports[27017] }}
        run: yarn test

      - name: Run mutation tests
        run: yarn test:mutation
        env:
          STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}
